[Suggestion] Allow GitHubRunner as a project setting
microsoft/AL-Go pull request #1177
Opened 2024-08-23 13:11 UTC by aholstrup1

Allow GitHubRunner as a project setting. This would enable us to compile apps on linux-based GitHub runners while running the tests on either windows GitHub runners or self-hosted runners.

2024-08-28 06:46 UTC, freddydk commented
These lines at the end of ReadSettings should be removed:

```
$gitHubRunner = $settings.githubRunner.Split(',').Trim() | ConvertTo-Json -compress
Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "GitHubRunnerJson=$githubRunner"
Write-Host "GitHubRunnerJson=$githubRunner"

$gitHubRunnerShell = $settings.githubRunnerShell
Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "GitHubRunnerShell=$githubRunnerShell"
Write-Host "GitHubRunnerShell=$githubRunnerShell"
```
and these lines in the corresponding action.yaml:
```
outputs:
  GitHubRunnerJson:
    description: GitHubRunner in compressed Json format
    value: ${{ steps.readsettings.outputs.GitHubRunnerJson }}
  GitHubRunnerShell:
    description: Shell for GitHubRunner jobs
    value: ${{ steps.readsettings.outputs.GitHubRunnerShell }}
```
and these lines in the corresponding readme.md should be replaced by `none`:
```
| Name | Description |
| :-- | :-- |
| GitHubRunnerJson | GitHubRunner in compressed Json format |
| GitHubRunnerShell | Shell for GitHubRunner jobs |
```

2024-08-28 06:48 UTC, freddydk requested changes
Looks good - I like the change
Added a comment with requested changes (to remove the outputs from ReadSettings)

2024-09-02 12:14 UTC, aholstrup1 commented
> Looks good - I like the change Added a comment with requested changes (to remove the outputs from ReadSettings)

So.. We're still using these outputs a couple of places. Specifically, in BuildPP:
https://github.com/microsoft/AL-Go/blob/67b44892165e183e6a550a90c3d909e32604772e/Templates/Per%20Tenant%20Extension/.github/workflows/CICD.yaml#L174-L175

And CreateDevelopmentEnvironment
https://github.com/microsoft/AL-Go/blob/67b44892165e183e6a550a90c3d909e32604772e/Templates/AppSource%20App/.github/workflows/CreateOnlineDevelopmentEnvironment.yaml#L103

How do we get rid of those dependencies in an appropriate way?

2024-09-05 08:55 UTC, mazhelez approved these changes

2024-09-05 08:55 UTC, mazhelez commented on Actions/AL-Go-TestRepoHelper.ps1
>          # GitHubRunner should not be in a project settings file (only read from repo or workflow settings)
Comment should be removed as well.

2024-09-05 12:49 UTC, mazhelez approved these changes

2024-09-05 14:12 UTC, freddydk approved these changes

2024-09-09 10:10 UTC, merged